### ISSUE TITLE
Logo image not loading

### ISSUE THREAD

**Issue by KevinRebakure** [Mydeen96/Static-page#1]
![Screenshot 2024-08-18 185609](https://github.com/user-attachments/assets/89641a45-505d-4aa5-b451-3791c00d6782)

1. Assets added to the public folder are registered on the root path by default. You don't to do '.../.../public'. Just access the public directory as './'
![Screenshot 2024-08-18 191401](https://github.com/user-attachments/assets/fde8de8b-75b5-4149-adb0-01d6dacc6f9a)

2. Also work on the folder structure a little bit to use the best practices. Take everything out of "static-page" directory.

**Comment by Mydeen96** [comment]
Thank you soo much for your feedback
